### ISSUE TITLE
"triangularDistributedLoad" function in PrairieDraw.js Library 

### ISSUE THREAD

**Issue by vineethbodapati** [PrairieLearn/PrairieLearn#1262]
I am trying to create a triangular distributed load using the function "triangularDistributedLoad(start, end, startSize, endSize, startLabel, endLabel, arrowToLine, arrowDown)".  But when I make the 'startSize' as zero I cannot render the diagram and If I use a smaller value, say 0.1, for the 'startSize' I end up getting something like this.

Thanks
<img width="488" alt="capture_3" src="https://user-images.githubusercontent.com/38234287/45705692-de32b900-bb3f-11e8-8580-1003eb4e24cd.PNG">

**Comment by mwest1066** [comment]
I gather that if startSize=1 and endSize=0.01 then everything works fine (the triangular distributed load renders correctly). But if startSize=0.01 and endSize=1 then you get something like the picture above (the triangular distributed load has a huge number of arrows inside it, so it appears almost solid).

**Comment by mfsilva22** [comment]
Can I get the QID of the above question? And I assume this is for TAM 210?

**Comment by mwest1066** [comment]
I'm not sure whether @vineethbodapati is tracking this issue. Maybe it's worth asking @w-chang?

**Comment by vineethbodapati** [comment]
The QID for the question is "distributedforce4" and it is in TAM 210/211. Currently, the question is still in the previous version (uses an image to render the diagram), so you may not see the problem that I have mentioned in my post. I haven't committed to the master yet.

Thanks
Vineeth
________________________________

**Comment by mwest1066** [comment]
Vineeth, can you put the new code somewhere that @mfsilva22 can see it so she can fix the bug? You could even just email it to her directly.

**Comment by vineethbodapati** [comment]
________________________________

**Comment by vineethbodapati** [comment]
I emailed my code the same day. I was wondering if you have received my email or not. Thanks!

**Comment by mfsilva22** [comment]
No, I didn't receive any email with coding. Would you be able to just commit it to master? You can add a tag indicating it is a broken question, or wip?

**Comment by vineethbodapati** [comment]
Sure. I can do that.

**Comment by vineethbodapati** [comment]
I just committed it to master. 
Sorry about the confusion and multiple e-mails.

**Comment by mfsilva22** [comment]
what is the question name (QID)?

**Comment by vineethbodapati** [comment]
distributedforce4

**Comment by mfsilva22** [comment]
Unless I am missing out something, I don't think `distributedforce4` is a broken question (the one you are saying you were converting to use PL drawing). I still see the question importing a figure. I need to have access to the broken question that you used to generate the picture above, otherwise, it will take me a long time to reproduce the same error.
